import type { Task } from "@/models";
import { TaskStatus, TaskPriority } from "@/models";
import { v4 as uuidv4 } from "uuid";

export function exportTasksToJSON(
  tasks: Task[],
  filename = "tasks.json",
): void {
  const dataStr = JSON.stringify(tasks, null, 2);
  const dataBlob = new Blob([dataStr], { type: "application/json" });
  const url = URL.createObjectURL(dataBlob);

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export interface ValidationError {
  taskIndex: number;
  field: string;
  message: string;
  taskTitle?: string;
}

export interface ValidationResult {
  isValid: boolean;
  errors: ValidationError[];
  validTasks: Task[];
  invalidTasksCount: number;
  totalTasks: number;
}

function validateTask(task: unknown, index: number): ValidationError[] {
  const errors: ValidationError[] = [];

  if (!task || typeof task !== "object") {
    errors.push({
      taskIndex: index,
      field: "task",
      message: "Task must be an object",
    });
    return errors;
  }

  const t = task as Record<string, unknown>;
  const taskTitle = typeof t.title === "string" ? t.title : `Task ${index}`;
  // Validate id (UUID v4, required, unique, generated by the server)
  if (!t.id || typeof t.id !== "string" || t.id.trim() === "") {
    t.id = uuidv4();
  }

  // Validate title (required, min 3, max 100, no whitespace-only)
  if (!t.title || typeof t.title !== "string") {
    errors.push({
      taskIndex: index,
      field: "title",
      message: "'title' is required",
      taskTitle,
    });
  } else {
    if (t.title.trim() === "") {
      errors.push({
        taskIndex: index,
        field: "title",
        message: "'title' cannot be empty or whitespace only",
        taskTitle,
      });
    }
    if (t.title.length < 3) {
      errors.push({
        taskIndex: index,
        field: "title",
        message: "'title' must be at least 3 characters",
        taskTitle,
      });
    }
    if (t.title.length > 100) {
      errors.push({
        taskIndex: index,
        field: "title",
        message: "'title' must not exceed 100 characters",
        taskTitle,
      });
    }
  }

  // Validate description (max 500)
  if (typeof t.description !== "string") {
    errors.push({
      taskIndex: index,
      field: "description",
      message: "'description' must be a string",
      taskTitle,
    });
  } else if (t.description.length > 500) {
    errors.push({
      taskIndex: index,
      field: "description",
      message: "'description' must not exceed 500 characters",
      taskTitle,
    });
  }

  // Validate status
  if (!Object.values(TaskStatus).includes(t.status as TaskStatus)) {
    errors.push({
      taskIndex: index,
      field: "status",
      message: `Invalid 'status'. Must be one of: ${Object.values(TaskStatus).join(", ")}`,
      taskTitle,
    });
  }

  // Validate priority
  if (!Object.values(TaskPriority).includes(t.priority as TaskPriority)) {
    errors.push({
      taskIndex: index,
      field: "priority",
      message: `Invalid 'priority'. Must be one of: ${Object.values(TaskPriority).join(", ")}`,
      taskTitle,
    });
  }

  // Validate createdAt (auto-generate if missing)
  if (!t.createdAt || typeof t.createdAt !== "string") {
    t.createdAt = new Date().toISOString();
  } else if (isNaN(Date.parse(t.createdAt))) {
    errors.push({
      taskIndex: index,
      field: "createdAt",
      message: "'createdAt' is not a valid date",
      taskTitle,
    });
  }

  // Validate updatedAt
  if (t.updatedAt !== null && typeof t.updatedAt !== "string") {
    errors.push({
      taskIndex: index,
      field: "updatedAt",
      message: "'updatedAt' must be a string or null",
      taskTitle,
    });
  } else if (t.updatedAt && isNaN(Date.parse(t.updatedAt))) {
    errors.push({
      taskIndex: index,
      field: "updatedAt",
      message: "'updatedAt' is not a valid date",
      taskTitle,
    });
  }

  // Validate dueDate (allow past dates for imports)
  if (t.dueDate !== null && typeof t.dueDate !== "string") {
    errors.push({
      taskIndex: index,
      field: "dueDate",
      message: "'dueDate' must be a string or null",
      taskTitle,
    });
  } else if (t.dueDate) {
    const dueDateParsed = Date.parse(t.dueDate);
    if (isNaN(dueDateParsed)) {
      errors.push({
        taskIndex: index,
        field: "dueDate",
        message: "'dueDate' is not a valid date",
        taskTitle,
      });
    }
  }

  return errors;
}

function validateAllTasks(tasks: unknown[]): ValidationResult {
  const allErrors: ValidationError[] = [];
  const validTasks: Task[] = [];

  tasks.forEach((task, index) => {
    const taskErrors = validateTask(task, index);

    if (taskErrors.length === 0) {
      validTasks.push(task as Task);
    } else {
      allErrors.push(...taskErrors);
    }
  });

  return {
    isValid: allErrors.length === 0,
    errors: allErrors,
    validTasks,
    invalidTasksCount: tasks.length - validTasks.length,
    totalTasks: tasks.length,
  };
}

export function importTasksFromJSON(file: File): Promise<ValidationResult> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = (event) => {
      try {
        const content = event.target?.result as string;
        const tasks = JSON.parse(content);

        if (!Array.isArray(tasks)) {
          reject(new Error("Invalid JSON format: expected an array of tasks"));
          return;
        }

        if (tasks.length === 0) {
          reject(new Error("No tasks found in the file"));
          return;
        }

        const validationResult = validateAllTasks(tasks);
        resolve(validationResult);
      } catch (error) {
        if (error instanceof SyntaxError) {
          reject(new Error("Invalid JSON file: " + error.message));
        } else {
          reject(error);
        }
      }
    };

    reader.onerror = () => {
      reject(new Error("Failed to read file"));
    };

    reader.readAsText(file);
  });
}
